### ISSUE TITLE
Rules with very long conclusion and >1 very short premises look cringe

### ISSUE THREAD

**Issue by ice1000** [pauladam94/curryst#17] opened 2024-05-06 22:59 UTC
For instance

```typ
#import "@preview/curryst:0.3.0": rule, proof-tree
$
#proof-tree(rule(
  "crrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiinnnnnnnnnnnnnnnnnnnnnnnnnnnnge",
  "premise1",
  "premise2"
))
$
```

looks like
![image](https://github.com/pauladam94/curryst/assets/16398479/65c9a535-b3e9-4cce-bd12-d2203e79435b)

But if it exceeds a certain line width, it looks fine:

```typ
#import "@preview/curryst:0.3.0": rule, proof-tree
$
#proof-tree(rule(
  "even more crrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrriiiiiiiiinnnnnnnnnnnnnnnnnnnnnnnnnnnnge idk",
  "premise1",
  "premise2"
))
$
```

![image](https://github.com/pauladam94/curryst/assets/16398479/3e7968c5-05ed-4fae-86ad-8f1a19466342)

**Comment by MDLC01** [comment] 2024-05-07 05:57
For context, the "cringe" behavior is the intended behavior. The second behavior you showed is unintended, and likely due to the total width of the tree exceeding the width of the page. Note that the second behavior does not occur if at least one of the premises is itself a rule. For example:

```typ
#proof-tree(rule(
  [Loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong conclusion],
  rule[Premise 1],
  rule[Premise 2],
))
```
![The premises are axioms. They are laid out in the "cringe" way.](https://github.com/pauladam94/curryst/assets/57839069/90d6345b-c694-4aaf-9057-f2c44584f3de)

Now the question is what exactly would be the desired behavior. The second image you posted does not look great to me either.

**Comment by ice1000** [comment] 2024-05-07 09:56
I kinda want the first one to be not that far away

**Comment by ice1000** [comment] 2024-05-07 09:57
It is true that when writing proof trees that one is based, but when presenting rules it's kinda cringe. I also don't know how to workaround it

**Comment by pauladam94** [comment] 2024-05-09 09:51
I think the behavior we want to have. Which is none of both of them.

In this example with two rules, we have a lot of white space to manage at the top of the rule. It might be smart to spread it evenly between :
- the left of the left rule
- between the two rules 
- the right of the right rule

However, I think this issue is mainly related to the fact that we try to have the same behavior for very high tree and for simple rules. (even if we already have some different behavior for those). It might be a good idea to separate the two behavior in the code.

We will also add those examples you proposed to make sure this issue is fixed in all future version.

**Comment by pauladam94** [comment] 2024-05-09 10:20
I have read again the [documentation of mathpartir](https://ctan.org/pkg/mathpartir). It's a latex package that does inference rule pretty well. Is it the main reason why we have chosen for now the first behavior (very far away premises).

**Comment by ice1000** [comment] 2024-05-09 14:53
> However, I think this issue is mainly related to the fact that we try to have the same behavior for very high tree and for simple rules. (even if we already have some different behavior for those). It might be a good idea to separate the two behavior in the code.

I strongly agree!

**Closed** 2024-05-26 11:11 UTC
